# Generated by Django 2.2 on 2020-07-28 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0007_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-created"]},
        ),
        migrations.AlterUniqueTogether(
            name="follow", unique_together={("user", "author")},
        ),
    ]
